# Publications — auto-cited via DOI using manubot

- id: doi:10.1101/2024.08.13.607832
  date: 2024-08-14
  tags:
    - organoids
    - imaging

- id: doi:10.1038/s41588-023-01435-6
  date: 2023-07-13
  tags:
    - spatial transcriptomics
    - mouse embryo

- id: doi:10.1038/s41587-021-01094-0
  date: 2022-01-10
  tags:
    - cell lineage
    - machine learning

- id: doi:10.1126/science.aba4937
  date: 2020-12-04
  tags:
    - gastruloids
    - mouse

- id: doi:10.1126/science.aar5663
  date: 2020-07-03
  tags:
    - ascidian
    - morphogenesis
    - cell communication

- id: doi:10.7554/eLife.34410
  date: 2018-04-09
  tags:
    - cell lineage
    - arthropod

- id: doi:10.1016/j.cell.2018.09.031
  date: 2018-10-04
  tags:
    - mouse embryo
    - cell tracking

- id: doi:10.15252/embr.201439123
  date: 2015-02-06
  tags:
    - ER stress

- id: doi:10.1109/ISBI.2015.7163872
  date: 2015-04-01
  tags:
    - registration
    - ascidian

- id: doi:10.1109/ISBI.2014.6867986
  date: 2014-04-01
  tags:
    - registration
    - embryo

- id: doi:10.1109/ISBI.2014.6868105
  date: 2014-04-01
  tags:
    - segmentation
    - embryo
